---
version: '3.7'

services:
  whoami:
    image: "containous/whoami"
    restart: unless-stopped
    networks:
      - default
    labels:
      - traefik.enable=true
      - "traefik.http.routers.${NAME}.rule=Host(`${NAME}.${DOMAIN}`)"
      - "traefik.http.routers.${NAME}.entrypoints=web-secure"
      - "traefik.http.routers.${NAME}.tls=true"

networks:
  default:
    external:
      name: gateway
